version: "3"
services:
  app:
    container_name: "app"
    volumes:
      - ./:/code
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    command: "gin server"
    environment:
      DB_USER: root
      DB_PASSWORD: app
      DB_NAME: app
      DB_HOST: db
  db:
    image: "mysql:5.7"
    container_name: "db"
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=app"
    ports:
      - "3306:3306"
